data:
  block_size: 512
  duration: 1
  encoder: contentvec768l12
  encoder_ckpt: pretrain/contentvec/checkpoint_best_legacy_500.pt
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  - flac
  f0_extractor: rmvpe
  f0_max: 1200
  f0_min: 40
  sampling_rate: 44100
  train_path: data/测试/train
  valid_path: data/测试/valid
device: cuda
env:
  expdir: exp/reflowvae-wavenet-attention_测试
  gpu_id: 0
infer:
  infer_step: 50
  method: euler
model:
  back_bone: wavenet
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spk: 1
  type: RectifiedFlow_VAE
  use_attention: true
  use_pitch_aug: false
train:
  amp_dtype: fp16
  batch_size: 50
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  decay_step: 250000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 10000
  interval_log: 100
  interval_val: 5000
  lr: 0.0005
  num_workers: 2
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
z_spk_dict:
  Popcs: 0
