data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 1
  encoder: contentvec768l12
  encoder_ckpt: pretrain/contentvec/checkpoint_best_legacy_500.pt
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  - flac
  f0_extractor: rmvpe
  f0_max: 1200
  f0_min: 40
  sampling_rate: 44100
  train_path: data/train
  valid_path: data/val
device: cuda
env:
  expdir: exp/reflowvae-wavenet
  gpu_id: 0
infer:
  infer_step: 10
  method: rk4
model:
  back_bone: wavenet
  n_chans: 768
  n_hidden: 256
  n_layers: 30
  n_spk: 16
  type: RectifiedFlow_VAE
  use_pitch_aug: true
spk_dict:
  Opencpop: 1
  Popcs: 2
train:
  amp_dtype: fp16
  batch_size: 150
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  decay_step: 50000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 10000
  interval_log: 100
  interval_val: 5000
  lr: 0.00015
  num_workers: 4
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/fish/firefly-gan-base-generator.ckpt
  type: fish
